baseURL = 'http://tumuchdata.org/'
languageCode = 'en-us'
title = 'TUMuchData'
theme = 'nightfall'

[params]
dateFormat = "02.01.2006"
site_logo="images/logo_white.svg"
hostname = "tumuchdata.club"
user = "db"
title = "TUMuchData"
subtitle = "The Munich Database Club"
showMetadata = false

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files

[taxonomies]
author = "authors"
tag = "tags"
